import { useState } from 'react'
import { Chevron, Cloche } from '../components/Icones'
import './live.css'

function Symbole({ replay = false, taille = 23 }: { replay?: boolean; taille?: number }) {
  return <svg width={taille} height={taille} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{replay ? <><path d="M3 11a9 9 0 1 1 2 7M1 8l2 5 4-3"/><path d="m10 7 7 5-7 5Z" fill="currentColor" stroke="none"/></> : <><rect x="3" y="5" width="18" height="17" rx="2"/><path d="M7 2v6M17 2v6"/><path d="m12 9 1.55 3.14 3.47.51-2.51 2.44.59 3.45L12 16.91l-3.1 1.63.59-3.45-2.51-2.44 3.47-.51Z"/></>}</svg>
}
function Interrupteur({ titre, actif, changer }: { titre: string; actif: boolean; changer: () => void }) {
  return <button className={`live-switch ${actif ? 'active' : ''}`} role="switch" aria-label={titre} aria-checked={actif} onClick={changer}><span/></button>
}
type Ecran = 'accueil' | 'evenements' | 'promotion' | 'creer' | 'enregistrements' | 'reglages' | 'aide' | 'moderateurs' | 'publications'
type Evenement = { nom: string; date: string; duree: string; description: string; adultes: boolean }
export default function Live({ onRetour }: { onRetour: () => void }) {
  const [ecran, setEcran] = useState<Ecran>('accueil')
  const [onglet, setOnglet] = useState('Créés')
  const [replay, setReplay] = useState('Temps forts')
  const [options, setOptions] = useState<Record<string,boolean>>({})
  const [banniere, setBanniere] = useState(true)
  const [nom, setNom] = useState('')
  const [date, setDate] = useState('')
  const [duree, setDuree] = useState('60')
  const [description, setDescription] = useState('')
  const [datesOuvertes, setDatesOuvertes] = useState(false)
  const [evenements, setEvenements] = useState<Evenement[]>([])
  const [erreur, setErreur] = useState('')
  const [origineAide, setOrigineAide] = useState<Ecran>('evenements')
  const changer = (cle: string) => setOptions(o => ({...o,[cle]:!o[cle]}))
  const aide = () => {setOrigineAide(ecran);setEcran('aide')}
  const retour = () => {
    if (ecran === 'accueil') onRetour()
    else setEcran(ecran === 'aide' ? origineAide : ecran === 'moderateurs' ? 'reglages' : ecran === 'reglages' || ecran === 'publications' ? 'enregistrements' : ecran === 'creer' || ecran === 'promotion' ? 'evenements' : 'accueil')
  }
  const titres: Record<Ecran,string> = {accueil:'LIVE',evenements:'Événements LIVE',promotion:'Paramètres de l’événement',creer:'',enregistrements:'Enregistrements de LIVE',reglages:'Paramètres',aide:'Aide LIVE',moderateurs:'Modérateurs et modératrices',publications:''}
  const reglage = (cle:string,titre:string,texte:string) => <div className="live-reglage" key={cle}><div><h2>{titre}</h2><Interrupteur titre={titre} actif={!!options[cle]} changer={() => changer(cle)}/></div><p>{texte}</p></div>
  return <div className={`live-page live-${ecran}`}>
    <header className="live-header"><button aria-label="Retour" onClick={retour}><Chevron taille={24}/></button><h1>{titres[ecran]}</h1><div className="live-header-actions">
      {ecran === 'evenements' && <><button aria-label="Paramètres de l’événement" onClick={() => setEcran('promotion')}>•••</button><button aria-label="Aide" onClick={aide}><span className="live-aide-icone">?</span></button></>}
      {ecran === 'enregistrements' && <><button aria-label="Publications vidéo" onClick={() => setEcran('publications')}><svg width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinejoin="round"><path d="M15 3H5a2 2 0 0 0-2 2v15a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V10"/><path d="m9 9 6 4-6 4Z" fill="currentColor" stroke="none"/><path d="m19 0 1.4 3.6L24 5l-3.6 1.4L19 10l-1.4-3.6L14 5l3.6-1.4Z" fill="currentColor" stroke="none"/></svg></button><button aria-label="Paramètres des enregistrements" onClick={() => setEcran('reglages')}><svg width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="m9 2-1 3-3 1-2 4 2 2-1 4 3 3 3-1 3 3 4-2 1-3 3-2-1-4-3-1-1-4Z"/><circle cx="12" cy="12" r="4"/></svg></button></>}
      {ecran === 'reglages' && <button aria-label="Aide" onClick={aide}><span className="live-aide-icone">?</span></button>}
    </div></header>
    {ecran === 'accueil' && <div className="live-carte live-menu">{['Événements LIVE','Enregistrements de LIVE'].map((t,i)=><button key={t} onClick={() => setEcran(i ? 'enregistrements' : 'evenements')}><Symbole replay={!!i}/><span>{t}</span><Chevron taille={18}/></button>)}</div>}
    {ecran === 'evenements' && <><div className="live-tabs" role="tablist" aria-label="Événements">{['Créés','Inscrit(e)'].map(t=><button role="tab" aria-selected={onglet===t} key={t} className={onglet===t?'actif':''} onClick={() => setOnglet(t)}>{t}</button>)}</div>
      {onglet === 'Créés' ? <>{evenements.length ? <div className="live-liste">{evenements.map((e,i)=><article className="live-carte" key={i}><h2>{e.nom}</h2><p>{new Date(e.date).toLocaleString('fr-FR')} · {e.duree} min</p><p>{e.description}</p><small>Brouillon local{e.adultes ? ' · Public 18+' : ''} — non publié</small></article>)}</div> : <div className="live-presentation"><h2>Crée un événement pour<br/>ton prochain LIVE</h2><div><Symbole/><section><h3>Annonce ton programme LIVE</h3><p>Le lien de l’événement apparaîtra sur tes vidéos promotionnelles et ta page de profil. Les spectateurs peuvent s’inscrire en avance.</p></section></div><div><Cloche taille={24}/><section><h3>Garde les spectateurs au courant</h3><p>Les followers et les spectateurs inscrits recevront une notification au début de l’événement.</p></section></div></div>}<button className="live-principal live-bas" onClick={() => {setErreur('');setEcran('creer')}}>Créer un événement</button></> : <div className="live-vide"><Symbole taille={76}/><h2>Pas d’événements LIVE enregistrés</h2><p>Explore et participe à plus d’événements LIVE</p></div>}
    </>}
    {ecran === 'promotion' && <div className="live-carte">{reglage('promotion','Promotion d’événements à venir','Promeus les événements LIVE sur tes vidéos. Seul ton prochain événement à venir sera promu. Les liens vers les événements ne seront affichés que dans « Pour toi » et « Suivis ».')}</div>}
    {ecran === 'creer' && <form className="live-form" onSubmit={e => {e.preventDefault();if(new Date(date).getTime()<=Date.now()){setErreur('Choisis une date et une heure futures.');return}setEvenements(l=>[...l,{nom:nom.trim(),date,duree,description,adultes:!!options.adultes}]);setNom('');setDescription('');setDate('');setOnglet('Créés');setEcran('evenements')}}>
      <h2>Créer un événement</h2><label htmlFor="live-nom">Nom de l’événement <em>*</em></label><div className="live-champ"><input id="live-nom" required maxLength={32} placeholder="Saisis le nom de l’événement" value={nom} onChange={e=>setNom(e.target.value)}/><span>{nom.length}/32</span></div>
      <label>Date et heure <em>*</em></label><button type="button" className="live-champ live-date" aria-expanded={datesOuvertes} onClick={()=>setDatesOuvertes(!datesOuvertes)}>{date ? new Date(date).toLocaleString('fr-FR') : 'Définis une heure de début et une durée'}<span>⌄</span></button>{datesOuvertes && <div className="live-dates"><label htmlFor="live-date">Début</label><input id="live-date" type="datetime-local" required value={date} onChange={e=>setDate(e.target.value)}/><label htmlFor="live-duree">Durée</label><select id="live-duree" value={duree} onChange={e=>setDuree(e.target.value)}>{[30,60,90,120].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></div>}
      <label htmlFor="live-type">Type ⓘ</label><select id="live-type" className="live-champ"><option>LIVE ordinaire</option></select>
      <label htmlFor="live-description">Description</label><div className="live-champ live-description"><textarea id="live-description" maxLength={200} placeholder="Décris en quoi consiste cet événement" value={description} onChange={e=>setDescription(e.target.value)}/><span>{description.length}/200</span></div>
      <div className="live-reglage"><div><h2>Contrôle du public ⓘ</h2><button type="button" role="switch" aria-label="Public de 18 ans ou plus" aria-checked={!!options.adultes} className={`live-switch ${options.adultes?'active':''}`} onClick={()=>changer('adultes')}><span/></button></div><p>Ce LIVE n’est accessible que pour les utilisateurs de 18 ans ou plus.</p></div>
      <p className="live-demo">Démonstration : création d’un brouillon local uniquement, sans diffusion ni notification.</p>{erreur && <p role="alert">{erreur}</p>}<button className="live-principal" disabled={!nom.trim() || !date}>Créer</button>
    </form>}
    {ecran === 'enregistrements' && <>{banniere && !options.notifications && <div className="live-banniere"><button aria-label="Fermer la suggestion" className="live-fermer" onClick={()=>setBanniere(false)}>×</button><h2>Recevoir des notifications en cas de nouveaux temps forts</h2><p>Reçois des notifications dans ta boîte de réception lorsque de nouveaux temps forts sont prêts à être publiés.</p><button className="live-activer" onClick={()=>changer('notifications')}>Activer</button></div>}<div className="live-tabs" role="tablist" aria-label="Enregistrements">{['Temps forts','Rediffusions','Clips'].map(t=><button key={t} role="tab" aria-selected={replay===t} className={replay===t?'actif':''} onClick={()=>setReplay(t)}>{t}</button>)}</div><div className="live-vide live-replays"><Symbole replay taille={92}/><h2>{replay==='Temps forts'?'Aucun temps fort pour le moment':replay==='Clips'?'Aucun clip pour le moment':'Aucune rediffusion pour le moment'}</h2><p>{replay==='Temps forts'?'Les temps forts sont générés automatiquement à partir de tes diffusions LIVE.':'Tes enregistrements apparaîtront ici après tes diffusions LIVE.'}</p></div></>}
    {ecran === 'reglages' && <><div className="live-carte">{reglage('notifications','Recevoir des notifications en cas de nouveaux temps forts','Reçois des notifications dans ta boîte de réception lorsque de nouveaux temps forts sont prêts à être publiés.')}</div><div className="live-carte">{reglage('fans','Fan Club','Une fois cette option activée, les fans de ton Fan Club pourront publier des temps forts de tes LIVE.')}{reglage('invites','Partager les enregistrements avec les invités','Après chaque LIVE multi-invité, les invité(e)s reçoivent les enregistrements par le biais de notifications dans leur boîte de réception.')}<div className="live-reglage"><button className="live-moderateurs" onClick={()=>setEcran('moderateurs')}><h2>Partager les enregistrements avec les modérateur(trice)s</h2><span>0 ›</span></button><p>Après chaque LIVE, les modérateur(trice)s sélectionné(e)s reçoivent les enregistrements par le biais de notifications dans leur boîte de réception.</p></div>{reglage('donateurs','Partager des temps forts avec les donateur(trice)s','Après chacun de tes LIVE, tes donateur(trice)s reçoivent leurs temps forts via des notifications dans leur boîte de réception.')}</div><p className="live-demo">Réglages de démonstration — les envois ne sont pas encore activés.</p></>}
    {ecran === 'aide' && <div className="live-carte"><h2>Événements et enregistrements LIVE</h2><p>Prépare un événement depuis l’onglet Créés. Les onglets Temps forts, Rediffusions et Clips regroupent les différents enregistrements.</p><p>Cette version présente le parcours : les événements restent des brouillons locaux et aucune diffusion, promotion ou notification n’est envoyée.</p></div>}
    {ecran === 'publications' && <><h1 className="live-publications-titre">Publications vidéo</h1>{['Tes publications', 'Partagées par d’autres personnes'].map((titre,i) => <section className="live-publications-carte" key={titre}><h2>{titre}</h2><div className="live-publications-vide"><svg width="145" height="100" viewBox="0 0 160 110" fill="none" aria-hidden="true"><path d="M30 13c-25 0-31 33-7 40 13 4 28-1 43 9-9-10-1-24-9-37-5-8-15-12-27-12Z" fill="#ddd"/><path d="m25 31-1 6m13-5v6m12-4-2 6" stroke="white" strokeWidth="4"/><g stroke="#bfbfbf" strokeWidth="3.5"><path d="M88 65c-9-21-8-48 10-49 13-2 20 7 25 15l9 8-7 7 1 15c18 8 25 18 29 33M82 40l45-22M98 40q3 8 7 0m4-4q4 8 8-1m-18 12q12 14 22-3M89 66c-22 4-35 15-29 24 7 6 15-10-10-18-18-6-31-4-17 3-26-4-38 7-18 8 20-1 30 3 35 13"/></g></svg><h3>Aucune publication pour le moment</h3><p>{i === 0 ? 'Les publications que tu crées à partir de tes enregistrements de LIVE s’affichent ici.' : 'Les publications créées par les autres personnes à partir des enregistrements de LIVE que tu partages s’affichent ici.'}</p></div></section>)}</>}
    {ecran === 'moderateurs' && <div className="live-vide"><h2>Aucun modérateur pour le moment</h2></div>}
  </div>
}
